In [1]:
## Forward simulator of haplotype frequencies with recombination


In [2]:
import numpy as np

In [3]:
# create generation 0 object
# set of original haplotypes which are sequences

In [4]:
# simulate a generation and create a generation object with contains haplotype objects

In [6]:
# a haplotype object looks like this
myparents = np.array(1)
myproportions = np.array(1)
H1_1 = np.column_stack((myparents, myproportions))
print(H1_1)

myparents = np.array(2)
myproportions = np.array(2)
H1_2 = np.column_stack((myparents, myproportions))
print(H1_2)

myparents = np.array(3)
myproportions = np.array(3)
H1_3 = np.column_stack((myparents, myproportions))
print(H1_3)

[[1 1]]
[[2 2]]
[[3 3]]


In [ ]:
# for loop Ncurrent times to create 2N haplotypes in the next generation
# to create each individual 3 functions are required

In [ ]:
# returns a 1D array containing 1 integer, the number of recombination events
get_recombinations (R=r*L) 

In [ ]:
# returns a 1D array containing the index of the parents of the haplotype drawn from the previous generation
get_parents (get_recombinations, Nprev)
numberOfparents = ((get_recombinations) + 1)

In [ ]:
# computes a 1D array of breakpoints, as many floats as recombination events drawn from a uniform normalised distribution
# returns a 1D array with proportions of each parent haplotype for descendant by computing differences between 0, successive breakpoints and 1  
get_proportions (get_recombinations)
breakpoints = sample_from_uniform_distribution
